Repository cloudposse/terraform-spacelift-cloud-infrastructure-automation, pull requests merged in 2022-01, with the labels that each got.

#81 Fix Spacelift stacks context filters
  .github/auto-release.yml
  LICENSE
  README.md
  main.tf
Labels: patch

#85 Fix: Properly Toggle Stack Destructor Functionality via `var.stack_destructor_enabled`
  README.md
  README.yaml
  modules/stack/main.tf
Labels: bug

#80 Fix: Update Variables and Locals in `examples/complete`
  README.md
  README.yaml
Labels: no-release
